name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # master 브랜치에 푸시될 때 트리거

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. 리포지토리 체크아웃
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Node.js 설치
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18  # 사용하는 Node.js 버전
        cache: 'npm'

    # 3. 의존성 설치
    - name: Install dependencies
      run: npm install

    # 4. Vite 빌드 실행
    - name: Build project
      run: npm run build

    # 5. GitHub Pages로 배포
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
